package io.titan.gradle;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TitanTranspileTaskTest {

    @TempDir
    Path tempDir;

    // GAP S8: the task no longer fingerprints its own inputs; when it runs it must regenerate
    // deterministically (unchanged artifacts are left byte-identical and a manually deleted
    // artifact reappears). Skipping reruns is exclusively Gradle's up-to-date check now.
    @Test
    void rerunsAreDeterministicAndRegenerateDeletedArtifacts() throws Exception {
        Project project = ProjectBuilder.builder().build();
        TitanTranspileTask task = project.getTasks().create("titanTranspileFingerprintTest", TitanTranspileTask.class);

        Path sourceDir = tempDir.resolve("src-fingerprint");
        Files.createDirectories(sourceDir.resolve("titan/dsl"));
        Files.createDirectories(sourceDir.resolve("demo"));

        Path annotationSource = sourceDir.resolve("titan/dsl/StoredProcedure.java");
        Files.writeString(annotationSource, """
                package titan.dsl;

                import java.lang.annotation.ElementType;
                import java.lang.annotation.Retention;
                import java.lang.annotation.RetentionPolicy;
                import java.lang.annotation.Target;

                @Retention(RetentionPolicy.RUNTIME)
                @Target(ElementType.METHOD)
                public @interface StoredProcedure {}
                """);

        Path entryPointSource = sourceDir.resolve("demo/EntryPoints.java");
        Files.writeString(entryPointSource, """
                package demo;

                import titan.dsl.StoredProcedure;

                class EntryPoints {
                    @StoredProcedure
                    public static void syncAccounts() {
                    }
                }
                """);

        task.getSourceFiles().from(annotationSource.toFile(), entryPointSource.toFile());
        task.getTargets().set(java.util.List.of("postgresql"));
        task.getOutputDir().set(tempDir.resolve("generated-sql-fingerprint").toFile());

        task.run();

        Path dialectDir = tempDir.resolve("generated-sql-fingerprint/postgresql");
        Path generatedSql = firstSqlFile(dialectDir);
        String firstContent = Files.readString(generatedSql);

        task.run();

        assertEquals(firstContent, Files.readString(generatedSql),
                "reruns over identical inputs must produce byte-identical SQL artifacts");
        assertFalse(Files.exists(tempDir.resolve("generated-sql-fingerprint/.titan-transpile.fingerprint")),
                "homegrown fingerprints are deleted (GAP S8); Gradle owns incrementality");

        Files.delete(generatedSql);
        task.run();

        assertTrue(Files.exists(generatedSql), "a deleted SQL artifact must be regenerated by the next run");
        assertEquals(firstContent, Files.readString(generatedSql));
    }

    @Test
    void removesStaleSqlArtifactsWhenEntryPointsAreRemoved() throws Exception {
        Project project = ProjectBuilder.builder().build();
        TitanTranspileTask task = project.getTasks().create("titanTranspileRemovedEntrypointsTest", TitanTranspileTask.class);

        Path sourceDir = tempDir.resolve("src-removed");
        Files.createDirectories(sourceDir.resolve("titan/dsl"));
        Files.createDirectories(sourceDir.resolve("demo"));

        Path annotationSource = sourceDir.resolve("titan/dsl/StoredProcedure.java");
        Files.writeString(annotationSource, """
                package titan.dsl;

                import java.lang.annotation.ElementType;
                import java.lang.annotation.Retention;
                import java.lang.annotation.RetentionPolicy;
                import java.lang.annotation.Target;

                @Retention(RetentionPolicy.RUNTIME)
                @Target(ElementType.METHOD)
                public @interface StoredProcedure {}
                """);

        Path entryPointSource = sourceDir.resolve("demo/EntryPoints.java");
        Files.writeString(entryPointSource, """
                package demo;

                import titan.dsl.StoredProcedure;

                class EntryPoints {
                    @StoredProcedure
                    public static void syncAccounts() {
                    }
                }
                """);

        task.getSourceFiles().from(annotationSource.toFile(), entryPointSource.toFile());
        task.getTargets().set(java.util.List.of("postgresql"));
        task.getOutputDir().set(tempDir.resolve("generated-sql-removed").toFile());

        task.run();

        Path dialectDir = tempDir.resolve("generated-sql-removed/postgresql");
        Path generatedSql = firstSqlFile(dialectDir);
        assertTrue(Files.exists(generatedSql));

        Files.writeString(entryPointSource, """
                package demo;

                class EntryPoints {
                    public static void syncAccounts() {
                    }
                }
                """);

        task.run();

        assertFalse(Files.exists(generatedSql), "stale SQL artifacts should be removed when no entry points remain");
    }

    @Test
    void removesStaleSqlArtifactsWhenDialectTargetIsRemoved() throws Exception {
        Project project = ProjectBuilder.builder().build();
        TitanTranspileTask task = project.getTasks().create("titanTranspileRemovedDialectTest", TitanTranspileTask.class);

        Path sourceDir = tempDir.resolve("src-removed-dialect");
        Files.createDirectories(sourceDir.resolve("titan/dsl"));
        Files.createDirectories(sourceDir.resolve("demo"));

        Path annotationSource = sourceDir.resolve("titan/dsl/StoredProcedure.java");
        Files.writeString(annotationSource, """
                package titan.dsl;

                import java.lang.annotation.ElementType;
                import java.lang.annotation.Retention;
                import java.lang.annotation.RetentionPolicy;
                import java.lang.annotation.Target;

                @Retention(RetentionPolicy.RUNTIME)
                @Target(ElementType.METHOD)
                public @interface StoredProcedure {}
                """);

        Path entryPointSource = sourceDir.resolve("demo/EntryPoints.java");
        Files.writeString(entryPointSource, """
                package demo;

                import titan.dsl.StoredProcedure;

                class EntryPoints {
                    @StoredProcedure
                    public static void syncAccounts() {
                    }
                }
                """);

        task.getSourceFiles().from(annotationSource.toFile(), entryPointSource.toFile());
        task.getTargets().set(java.util.List.of("postgresql", "mysql"));
        task.getOutputDir().set(tempDir.resolve("generated-sql-removed-dialect").toFile());

        task.run();

        Path mysqlDir = tempDir.resolve("generated-sql-removed-dialect/mysql");
        Path mysqlSql = firstSqlFile(mysqlDir);
        assertTrue(Files.exists(mysqlSql));

        task.getTargets().set(java.util.List.of("postgresql"));
        task.run();

        assertFalse(Files.exists(mysqlSql), "stale SQL artifacts from removed dialect targets should be cleaned up");
    }

    @Test
    void removesStaleSqlArtifactsFromPreviousEntryPoints() throws Exception {
        Project project = ProjectBuilder.builder().build();
        TitanTranspileTask task = project.getTasks().create("titanTranspileTest", TitanTranspileTask.class);

        Path sourceDir = tempDir.resolve("src");
        Files.createDirectories(sourceDir.resolve("titan/dsl"));
        Files.createDirectories(sourceDir.resolve("demo"));

        Path annotationSource = sourceDir.resolve("titan/dsl/StoredProcedure.java");
        Files.writeString(annotationSource, """
                package titan.dsl;

                import java.lang.annotation.ElementType;
                import java.lang.annotation.Retention;
                import java.lang.annotation.RetentionPolicy;
                import java.lang.annotation.Target;

                @Retention(RetentionPolicy.RUNTIME)
                @Target(ElementType.METHOD)
                public @interface StoredProcedure {}
                """);

        Path entryPointSource = sourceDir.resolve("demo/EntryPoints.java");
        Files.writeString(entryPointSource, """
                package demo;

                import titan.dsl.StoredProcedure;

                class EntryPoints {
                    @StoredProcedure
                    public static void syncAccounts() {
                    }
                }
                """);

        task.getSourceFiles().from(annotationSource.toFile(), entryPointSource.toFile());
        task.getTargets().set(java.util.List.of("postgresql"));
        task.getOutputDir().set(tempDir.resolve("generated-sql").toFile());

        task.run();

        Path dialectDir = tempDir.resolve("generated-sql/postgresql");
        assertTrue(Files.exists(dialectDir));

        Path stale = dialectDir.resolve("obsolete__legacy.sql");
        Files.writeString(stale, "SELECT 1;");
        assertTrue(Files.exists(stale));

        task.run();

        assertFalse(Files.exists(stale), "stale sql artifacts should be removed on subsequent transpile runs");
    }

    // B-2 (TG-BLK-005) shape 3: enum Operation and record Operation used to write the same
    // Operation__Operation.sql artifact file — one kind's DDL silently vanished from the
    // package. The kind token in the artifact file name keeps both on disk.
    @Test
    void enumAndRecordWithSameNameWriteDistinctArtifactFiles() throws Exception {
        Project project = ProjectBuilder.builder().build();
        TitanTranspileTask task = project.getTasks().create("titanTranspileCrossKindTest", TitanTranspileTask.class);

        Path sourceDir = tempDir.resolve("src-cross-kind");
        Files.createDirectories(sourceDir.resolve("alpha"));
        Files.createDirectories(sourceDir.resolve("beta"));

        Path enumSource = sourceDir.resolve("alpha/OperationEnum.java");
        Files.writeString(enumSource, """
                package alpha;

                enum Operation { CREATE, DELETE }
                """);
        Path recordSource = sourceDir.resolve("beta/OperationRecord.java");
        Files.writeString(recordSource, """
                package beta;

                record Operation(int id) {}
                """);

        task.getSourceFiles().from(enumSource.toFile(), recordSource.toFile());
        task.getTargets().set(java.util.List.of("postgresql"));
        task.getOutputDir().set(tempDir.resolve("generated-sql-cross-kind").toFile());

        task.run();

        Path dialectDir = tempDir.resolve("generated-sql-cross-kind/postgresql");
        Path enumArtifact = dialectDir.resolve("Operation__Operation.enum.sql");
        Path recordArtifact = dialectDir.resolve("Operation__Operation.record.sql");
        assertTrue(Files.exists(enumArtifact), "enum artifact file must be present");
        assertTrue(Files.exists(recordArtifact), "record artifact file must be present");
        assertTrue(Files.readString(enumArtifact).contains("__enum_operation"));
        assertTrue(Files.readString(recordArtifact).contains("__record_operation"));

        // Both rows must reference their on-disk artifact in the structured metadata.
        var metadata = TitanArtifactMetadataFile.read(
                tempDir.resolve("generated-sql-cross-kind").resolve(TitanArtifactMetadataFile.FILE_NAME));
        assertTrue(metadata.containsKey("postgresql/Operation__Operation.enum.sql"), metadata.keySet().toString());
        assertTrue(metadata.containsKey("postgresql/Operation__Operation.record.sql"), metadata.keySet().toString());
    }

    // B-7 (TG-BLK-001): strictWraparound is exposed through the plugin and reaches the pipeline.
    // The flag's effect is observable in the emitted SQL: int-typed `a + b` lowers to a plain `+`
    // by default, and to the java_int_add runtime helper (32-bit wrap parity) when set. Default
    // false matches the pipeline/lowerer default (fail-loud parity).
    @Test
    void strictWraparoundRewritesIntArithmeticToRuntimeHelper() throws Exception {
        Path sourceDir = tempDir.resolve("src-wraparound");
        Files.createDirectories(sourceDir.resolve("titan/dsl"));
        Files.createDirectories(sourceDir.resolve("demo"));

        Path annotationSource = sourceDir.resolve("titan/dsl/StoredFunction.java");
        Files.writeString(annotationSource, """
                package titan.dsl;

                import java.lang.annotation.ElementType;
                import java.lang.annotation.Retention;
                import java.lang.annotation.RetentionPolicy;
                import java.lang.annotation.Target;

                @Retention(RetentionPolicy.RUNTIME)
                @Target(ElementType.METHOD)
                public @interface StoredFunction {}
                """);

        Path entryPointSource = sourceDir.resolve("demo/Arithmetic.java");
        Files.writeString(entryPointSource, """
                package demo;

                import titan.dsl.StoredFunction;

                class Arithmetic {
                    @StoredFunction
                    public static int wrapAdd(int a, int b) {
                        return a + b;
                    }
                }
                """);

        // Default (flag unset): plain SQL addition, no runtime helper.
        String defaultSql = transpileWrapAdd(annotationSource, entryPointSource, null, "default");
        assertFalse(defaultSql.contains("java_int_add"),
                "without strictWraparound, int + must stay a plain SQL `+`:\n" + defaultSql);

        // strictWraparound = false explicitly: same as default.
        String falseSql = transpileWrapAdd(annotationSource, entryPointSource, false, "false");
        assertFalse(falseSql.contains("java_int_add"),
                "strictWraparound=false must not rewrite int arithmetic:\n" + falseSql);

        // strictWraparound = true: int + rewritten to the java_int_add runtime helper.
        String trueSql = transpileWrapAdd(annotationSource, entryPointSource, true, "true");
        assertTrue(trueSql.contains("java_int_add"),
                "strictWraparound=true must rewrite int + to the java_int_add runtime helper:\n" + trueSql);
    }

    private String transpileWrapAdd(
            Path annotationSource, Path entryPointSource, Boolean strictWraparound, String label)
            throws Exception {
        Project project = ProjectBuilder.builder().build();
        TitanTranspileTask task = project.getTasks()
                .create("titanTranspileWraparound_" + label, TitanTranspileTask.class);
        task.getSourceFiles().from(annotationSource.toFile(), entryPointSource.toFile());
        task.getTargets().set(java.util.List.of("postgresql"));
        if (strictWraparound != null) {
            task.getStrictWraparound().set(strictWraparound);
        }
        Path outputDir = tempDir.resolve("generated-sql-wraparound-" + label);
        task.getOutputDir().set(outputDir.toFile());

        task.run();

        return Files.readString(firstSqlFile(outputDir.resolve("postgresql")));
    }

    private static Path firstSqlFile(Path dir) throws Exception {
        try (var paths = Files.list(dir)) {
            return paths
                    .filter(path -> path.getFileName().toString().endsWith(".sql"))
                    .findFirst()
                    .orElseThrow();
        }
    }
}
