package io.titan.gradle;

import io.titan.transpiler.tir.DialectId;
import io.titan.transpiler.tir.SqlObject;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Renders the executable rollback artifact (plan 4.4, audit G-10 / production gate G4): one
 * {@code titan-rollback.sql} per dialect dropping every inventoried object in reverse
 * dependency order, with kind- and dialect-correct {@code DROP} syntax derived from the
 * structured metadata (PostgreSQL routine drops carry the typed argument list so overloads
 * resolve; triggers drop {@code ON} their table; MySQL events and triggers drop by name).
 *
 * <p>The prose "rollback hints" in the install plan stay as documentation; this script is the
 * executable counterpart.</p>
 */
final class TitanRollbackScript {

    private TitanRollbackScript() {
    }

    /** Package-root file name, e.g. {@code titan-rollback.postgresql.sql}. */
    static String fileNameFor(String dialect) {
        return "titan-rollback." + dialect + ".sql";
    }

    /**
     * One dialect's rendered rollback script with the integrity facts the manifest links to
     * (B-5): the relative package-root {@code path}, the {@code statementCount} and the
     * {@code sha256} of the script's raw UTF-8 bytes (no SQL normalization — the byte stream the
     * file holds, so a consumer hashing {@code Files.readString} of the file matches exactly).
     */
    record RenderedRollbackScript(String dialect, String path, String sql, int statementCount, String sha256) {
        TitanArtifactManifest.RollbackScript toManifestEntry() {
            return new TitanArtifactManifest.RollbackScript(dialect, path, statementCount, sha256);
        }
    }

    /** Renders every dialect's rollback script and the integrity facts the manifest links. */
    static List<RenderedRollbackScript> renderAll(
            List<String> dialects,
            String artifactId,
            List<TitanObjectInventory.GeneratedObject> inventoryObjects,
            Map<String, SqlObject> sqlObjectsByInventoryId,
            String mode
    ) {
        List<RenderedRollbackScript> rendered = new ArrayList<>();
        for (String dialect : dialects) {
            String sql = render(dialect, artifactId, inventoryObjects, sqlObjectsByInventoryId, mode);
            rendered.add(new RenderedRollbackScript(
                    dialect,
                    fileNameFor(dialect),
                    sql,
                    statementCount(sql),
                    TitanArtifactManifest.sha256Hex(sql.getBytes(java.nio.charset.StandardCharsets.UTF_8))));
        }
        return List.copyOf(rendered);
    }

    /**
     * Counts the {@code DROP} statements in a rendered rollback script: each rendered statement
     * is one {@code DROP ...;} per line, so a non-comment line ending in {@code ;} is one
     * statement (comment-only {@code -- titan:} lines for un-droppable objects are skipped). This
     * is the same convention titan-graphql's rollback summary uses, so the manifest's
     * {@code statementCount} equals what a consumer derives from the file.
     */
    static int statementCount(String sql) {
        int count = 0;
        for (String line : sql.split("\\R")) {
            String trimmed = line.trim();
            if (!trimmed.startsWith("--") && trimmed.endsWith(";")) {
                count++;
            }
        }
        return count;
    }

    static String render(
            String dialect,
            String artifactId,
            List<TitanObjectInventory.GeneratedObject> inventoryObjects,
            Map<String, SqlObject> sqlObjectsByInventoryId,
            String mode
    ) {
        List<TitanObjectInventory.GeneratedObject> dialectObjects = inventoryObjects.stream()
                .filter(object -> object.dialect().equals(dialect))
                .toList();
        List<TitanObjectInventory.GeneratedObject> reverseOrder =
                new ArrayList<>(TitanInstallPlan.installOrder(dialect, dialectObjects));
        java.util.Collections.reverse(reverseOrder);

        DialectId dialectId = DialectId.parse(dialect).orElse(null);
        StringBuilder script = new StringBuilder();
        script.append("-- titan-rollback for ").append(artifactId).append(" (").append(dialect).append(")\n");
        script.append("-- Generated by titanPackage from the object inventory; drops every Titan-generated\n");
        script.append("-- object in reverse dependency order. Review before executing: dropping tables\n");
        script.append("-- (enum lookups, titan_runtime.telemetry) discards their data.\n");
        if (dialectId == DialectId.POSTGRESQL) {
            script.append("-- pg_cron schedules registered for scheduled jobs are not catalog objects owned by\n");
            script.append("-- this package; unschedule them with cron.unschedule('<job-name>') if pg_cron is installed.\n");
        }
        script.append("\n");

        for (TitanObjectInventory.GeneratedObject object : reverseOrder) {
            SqlObject sqlObject = sqlObjectsByInventoryId.get(object.id());
            if (sqlObject == null || dialectId == null) {
                script.append("-- titan: no automatic rollback for ").append(object.id())
                        .append("; review ").append(object.sourceInputPath()).append(" manually.\n");
                continue;
            }
            script.append(dropStatement(dialectId, sqlObject)).append("\n");
        }

        if (dialectId == DialectId.POSTGRESQL && "migration".equals(mode)) {
            String runtimeNamespace = TitanPackagedArtifacts.runtimeNamespaceForDialect(dialect);
            if (!runtimeNamespace.isBlank()) {
                script.append("DROP SCHEMA IF EXISTS ").append(quotePostgres(runtimeNamespace)).append(";\n");
            }
        }
        return script.toString();
    }

    private static String dropStatement(DialectId dialectId, SqlObject object) {
        return switch (dialectId) {
            case POSTGRESQL -> postgresDrop(object);
            case MYSQL -> mysqlDrop(object);
        };
    }

    private static String postgresDrop(SqlObject object) {
        String qualified = qualifyPostgres(object.schema(), object.name());
        return switch (object.kind()) {
            // The typed argument list comes from the structured signature, so overloaded
            // routines (PostgreSQL supports overloading) resolve to the right definition.
            case FUNCTION -> "DROP FUNCTION IF EXISTS " + qualified + "(" + argumentTypes(object) + ");";
            case PROCEDURE -> "DROP PROCEDURE IF EXISTS " + qualified + "(" + argumentTypes(object) + ");";
            case TRIGGER -> "DROP TRIGGER IF EXISTS " + quotePostgres(object.name())
                    + " ON " + qualifyPostgresName(object.onTable()) + ";";
            case VIEW -> "DROP VIEW IF EXISTS " + qualified + ";";
            case TYPE -> "DROP TYPE IF EXISTS " + qualified + ";";
            case TABLE -> "DROP TABLE IF EXISTS " + qualified + ";";
            case EVENT -> "-- titan: PostgreSQL has no EVENT objects; nothing to drop for " + qualified + ".";
        };
    }

    private static String mysqlDrop(SqlObject object) {
        String qualified = qualifyMysql(object.schema(), object.name());
        return switch (object.kind()) {
            case FUNCTION -> "DROP FUNCTION IF EXISTS " + qualified + ";";
            case PROCEDURE -> "DROP PROCEDURE IF EXISTS " + qualified + ";";
            case TRIGGER -> "DROP TRIGGER IF EXISTS " + qualified + ";";
            case EVENT -> "DROP EVENT IF EXISTS " + qualified + ";";
            case VIEW -> "DROP VIEW IF EXISTS " + qualified + ";";
            case TABLE -> "DROP TABLE IF EXISTS " + qualified + ";";
            case TYPE -> "-- titan: MySQL has no composite types; nothing to drop for " + qualified + ".";
        };
    }

    private static String argumentTypes(SqlObject object) {
        return object.parameters().stream()
                .map(SqlObject.Parameter::type)
                .collect(Collectors.joining(", "));
    }

    /** Objects emitted without a schema (MySQL runtime helpers) drop unqualified. */
    private static String qualifyPostgres(String schema, String name) {
        if (schema == null || schema.isBlank()) {
            return quotePostgres(name);
        }
        return quotePostgres(schema) + "." + quotePostgres(name);
    }

    private static String qualifyPostgresName(String possiblyQualified) {
        int separator = possiblyQualified.lastIndexOf('.');
        if (separator < 0) {
            return quotePostgres(possiblyQualified);
        }
        return quotePostgres(possiblyQualified.substring(0, separator))
                + "." + quotePostgres(possiblyQualified.substring(separator + 1));
    }

    private static String qualifyMysql(String schema, String name) {
        if (schema == null || schema.isBlank()) {
            return quoteMysql(name);
        }
        return quoteMysql(schema) + "." + quoteMysql(name);
    }

    private static String quotePostgres(String identifier) {
        return '"' + identifier.replace("\"", "\"\"") + '"';
    }

    private static String quoteMysql(String identifier) {
        return '`' + identifier.replace("`", "``") + '`';
    }
}
