CREATE OR REPLACE FUNCTION "test"."failing"(p_value INTEGER)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
BEGIN
    IF COALESCE((p_value < 0), FALSE) THEN
        RAISE EXCEPTION USING ERRCODE = '45000', MESSAGE = 'TITAN_TZ_BOOM';
    END IF;
    RETURN p_value;
END;
$$;
